# Ce fichier docker-compose permet de lancer et d'orchestrer tous les services nécessaires à l'application:

# - Une base de données PostgreSQL pour stocker les données
# - Un serveur Redis pour la gestion du cache
# - Un backend Spring Boot pour la logique métier
# - Un frontend React/Next.js pour l'interface utilisateur

# Les services
# - Chaque service est isolé dans un conteneur et peut communiquer avec les autres.

# Les volumes
# - Ils assurent la persistance des données importantes (base de données, clés cryptographiques).
# - Un volume est utilisé par les conteneurs pour conserver les données même lorsque les conteneurs sont arrêtés ou supprimés.

# Les commandes
# -`docker-compose up` pour démarrer l'ensemble
# -`docker-compose down` pour arrêter


version: '3.8'
services:
  # Service pour la base de données PostgreSQL
  postgres:
    image: postgres:15
    container_name: identity_postgres
    # Variables d'environnement pour configurer PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identitydb
    # Expose le port 5433 du conteneur sur le port 5432 de la machine hôte
    ports:
      - "5433:5432"
    # Persiste les données dans un volume nommé
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Service pour le serveur Redis
  redis:
    image: redis:7
    container_name: identity_redis
    hostname: redis
    ports:
      - "6380:6379"
  # Service pour l'application Spring Boot
  backend:
    # Construit l'image à partir du Dockerfile situé dans ./backend
    build: ./backend
    container_name: identity_backend
    # Démarre ce service après le service postgres & redis
    depends_on:
      - postgres
      - redis
    # Variables d'environnement pour configurer la connexion à la base
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/identitydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    # Expose le port 8080 du conteneur sur le port 8080 de la machine hôte
    ports:
      - "8080:8080"
    #Permet de stocker les clés cryptographiques de l'application
    volumes:
      - crypto_keys:/app/keys
    # Redémarre le conteneur sauf si on l'arrête explicitement
    restart: unless-stopped
  # fronted est un service pour l'application Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: identity_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - backend
volumes:
  # Déclaration du volume pour persister les données PostgreSQL
  postgres_data:
  # Déclaration du volume pour stocker les clés cryptographiques
  crypto_keys:
    driver: local
